name: Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
    build:
        runs-on: ${{ matrix.platform.os }}
        name: ${{ matrix.platform.name }}

        steps:
        - uses: actions/checkout@v4

        - name: Build
          run: |
            cmake .
            cmake --build . --config Release
            cmake --install .  --prefix opengametools-install

        - name: Test
          run: |
            ctest -V -C Release .

        - name: Upload the build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: opengametools-${{ matrix.platform.name }}
            path: opengametools-install

        strategy:
          fail-fast: false
          matrix:
            platform:
            - { name: Windows,  os: windows-2022 }
            - { name: Ubuntu,   os: ubuntu-latest }
            - { name: MacOS,    os: macos-latest }
