name: Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
    linux:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Linux
          run: |
            g++ -Wall -Wextra -pedantic apps/vox2fbx.cpp
            g++ -Wall -Wextra -pedantic apps/vox2obj.cpp
            g++ -Wall -Wextra -pedantic apps/voxmerge.cpp
            g++ -Wall -Wextra -pedantic apps/voxseparate.cpp
